<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ojnexus</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OjNexus.Windows.Core\OjNexus.Windows.Core.csproj" />
  </ItemGroup>
</Project>
